# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  config,
  ...
}:

let
  services = [
    "vpn"         # wg-easy
    "jellyfin"    # jellyfin
    "iperf"       # speedtest-tracker
    "cloud"       # nextcloud
    "bag"         # wallabag
    "photos"       # immich
  ];
  subdomains = lib.concatStringsSep ", " services;
in
{

  # Ensure ix.local is resolvable (add to /etc/hosts)
  systemd.services."swag-ix-hosts-entry" = {
    description = "Add ix.local to /etc/hosts for Immich proxy";
    after = [ "network.target" ];
    before = [ "podman-swag.service" ];
    wantedBy = [ "multi-user.target" ];

    path = [ pkgs.coreutils pkgs.bash ];

    script = ''
      # Add ix.local to /etc/hosts if not already present
      if ! grep -q "^192.168.1.251.*ix.local" /etc/hosts; then
          echo "192.168.1.251 ix.local" >> /etc/hosts
      fi
    '';

    serviceConfig = {
      Type = "oneshot";
      User = "root";
    };
  };

  # Immich proxy config generation
  systemd.services."swag-immich-proxy-config" = {
    description = "Generate SWAG proxy config for Immich";
    after = [ "swag-ix-hosts-entry.service" ];
    before = [ "podman-swag.service" ];
    wantedBy = [ "multi-user.target" ];

    path = [ pkgs.coreutils pkgs.bash ];

    script = ''
      # Ensure proxy-confs directory exists
      mkdir -p /mnt/arrakis/swag/nginx/proxy-confs

      # Write Immich proxy config
      cat > /mnt/arrakis/swag/nginx/proxy-confs/immich.subdomain.conf << 'EOF'
      # Immich reverse proxy configuration
      # Generated by NixOS

      location / {
          include /config/nginx/proxy-confs/subfolder.conf;

          # Immich upload limits
          client_max_body_size 100M;
          client_body_timeout 600s;
          proxy_read_timeout 600s;
          proxy_send_timeout 600s;

          # Proxy settings
          include /config/nginx/proxy-confs/block-exploits.conf;
          include /config/nginx/proxy-confs/ssl-params.conf;
          include /config/nginx/proxy-confs/websocket.conf;

          # Upstream
          set $upstream http://ix.local:2283;
          proxy_pass $upstream;
      }

      # Support for Immich API routes
      location ^~ /api/ {
          include /config/nginx/proxy-confs/subfolder.conf;
          include /config/nginx/proxy-confs/ssl-params.conf;

          client_max_body_size 100M;
          client_body_timeout 600s;
          proxy_read_timeout 600s;
          proxy_send_timeout 600s;

          set $upstream http://ix.local:2283;
          proxy_pass $upstream;
      }
      EOF

      chown -R 1000:1000 /mnt/arrakis/swag/nginx/proxy-confs/immich.subdomain.conf
    '';

    serviceConfig = {
      Type = "oneshot";
      User = "root";
    };
  };

  # Containers
  virtualisation.oci-containers.containers."swag" = {
    image = "lscr.io/linuxserver/swag";
    environment = {
      "CERTPROVIDER" = "letsencrypt";
      "DNSPLUGIN" = "cloudflare";
      "EMAIL" = "dns@fjc.ar";
      "ONLY_SUBDOMAINS" = "false";
      "PGID" = "1000";
      "PUID" = "1000";
      "STAGING" = "false";
      "SUBDOMAINS" = subdomains;
      "TZ" = "America/Argentina/Cordoba";
      "URL" = "calvo.dev";
      "VALIDATION" = "http";
    };
    volumes = [ "/mnt/arrakis/swag:/config:rw" ];
    ports = [
      "443:443/tcp"
      "80:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--network-alias=swag"
      "--network=kaitain_default"
    ];
  };
  systemd.services."podman-swag" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-kaitain_default.service"
      "swag-ix-hosts-entry.service"
      "swag-immich-proxy-config.service"
    ];
    requires = [
      "podman-network-kaitain_default.service"
      "swag-ix-hosts-entry.service"
      "swag-immich-proxy-config.service"
    ];
    partOf = [ "podman-compose-kaitain-root.target" ];
    wantedBy = [ "podman-compose-kaitain-root.target" ];
  };

  # Ensure directories exist
  systemd.tmpfiles.rules = [
    "d /mnt/arrakis/swag 0755 1000 1000 -"
    "d /mnt/arrakis/swag/nginx/proxy-confs 0755 1000 1000 -"
  ];
}
