{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Networks
  systemd.services."podman-network-kaitain_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f kaitain_default";
    };
    script = ''
      podman network inspect kaitain_default || podman network create kaitain_default
    '';
    partOf = [ "podman-compose-kaitain-root.target" ];
    wantedBy = [ "podman-compose-kaitain-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-kaitain-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

  # Ensure swag directory exists
  systemd.tmpfiles.rules = [
    "d /mnt/arrakis/wg 0755 1000 1000 -"
  ];
}

