# Auto-generated by compose2nix and customized for Auto-Updating Site Configs.
{
  pkgs,
  lib,
  config,
  ...
}:
{
  # --- 1. SITE CONFIG UPDATE LOGIC ---
  # Keeps ftr-site-config rules updated for better article extraction
  # We still need to modify the service.yml to point Graby to the custom configs.
  # https://github.com/wallabag/wallabag/wiki/Auto%E2%80%90Updating-wallabag's-site%E2%80%90depended-config
  systemd.services.wallabag-site-config-update = {
    description = "Update Wallabag site-dependent configurations";
    after = [ "network.target" ];
    before = [ "podman-wallabag-wallabag.service" ];
    wantedBy = [ "multi-user.target" ];

    path = [
      pkgs.git
      pkgs.coreutils
      pkgs.bash
      pkgs.podman
    ];

    script = ''
      set -e
      mkdir -p /mnt/arrakis/wallabag/config

      # Fix Git "dubious ownership" error
      git config --global --add safe.directory /mnt/arrakis/wallabag/config/ftr-site-config

      # Clone or pull the site config repo
      if [ ! -d /mnt/arrakis/wallabag/config/ftr-site-config/.git ]; then
        git clone https://github.com/fivefilters/ftr-site-config /mnt/arrakis/wallabag/config/ftr-site-config
      else
        git -C /mnt/arrakis/wallabag/config/ftr-site-config pull
      fi

      # Extract services.yml from image and modify Graby config in one step
      podman run --rm wallabag/wallabag cat /var/www/wallabag/app/config/services.yml \
        | sed "s|\$config: {}|\$config: { site_config: ['/custom-configs'] }|g" \
        > /mnt/arrakis/wallabag/config/services.yml

      # Ensure permissions for the container (nobody/65534)
      chown -R 65534:65534 /mnt/arrakis/wallabag/config
    '';

    serviceConfig = {
      Type = "oneshot";
      User = "root";
    };
  };

  systemd.timers.wallabag-site-config-update = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true;
      Unit = "wallabag-site-config-update.service";
    };
  };

  # --- 2. CONTAINERS ---

  ## DB Container
  virtualisation.oci-containers.containers."wallabag-db" = {
    image = "mariadb";
    environmentFiles = [ "/mnt/arrakis/wallabag/.env" ];
    volumes = [ "/mnt/arrakis/wallabag/database:/var/lib/mysql" ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=/usr/local/bin/healthcheck.sh --innodb_initialized"
      "--health-interval=20s"
      "--health-timeout=3s"
      "--network-alias=db"
      "--network=wallabag_default"
    ];
  };

  systemd.services."podman-wallabag-db" = {
    serviceConfig.Restart = lib.mkOverride 90 "always";
    after = [ "podman-network-wallabag_default.service" ];
    requires = [ "podman-network-wallabag_default.service" ];
    partOf = [ "podman-compose-wallabag-root.target" ];
    wantedBy = [ "podman-compose-wallabag-root.target" ];
  };

  ## Redis Container
  virtualisation.oci-containers.containers."wallabag-redis" = {
    image = "redis:alpine";
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=redis-cli ping | grep PONG"
      "--health-interval=20s"
      "--health-timeout=3s"
      "--network-alias=redis"
      "--network=wallabag_default"
    ];
  };

  systemd.services."podman-wallabag-redis" = {
    serviceConfig.Restart = lib.mkOverride 90 "always";
    after = [ "podman-network-wallabag_default.service" ];
    requires = [ "podman-network-wallabag_default.service" ];
    partOf = [ "podman-compose-wallabag-root.target" ];
    wantedBy = [ "podman-compose-wallabag-root.target" ];
  };

  ## Wallabag Container
  virtualisation.oci-containers.containers."wallabag-wallabag" = {
    image = "wallabag/wallabag";
    environmentFiles = [ "/mnt/arrakis/wallabag/.env" ];
    volumes = [
      "/mnt/arrakis/wallabag/webserver:/var/www/wallabag/web/assets/images:rw"
      # Mounts for auto-updating site configs
      "/mnt/arrakis/wallabag/config/ftr-site-config:/custom-configs:ro"
      "/mnt/arrakis/wallabag/config/services.yml:/var/www/wallabag/app/config/services.yml:ro"
    ];
    ports = [ "8181:80/tcp" ];
    dependsOn = [
      "wallabag-db"
      "wallabag-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wallabag"
      "--network=wallabag_default"
    ];
  };

  systemd.services."podman-wallabag-wallabag" = {
    serviceConfig.Restart = lib.mkOverride 90 "always";
    after = [
      "podman-network-wallabag_default.service"
      "wallabag-site-config-update.service"
    ];
    requires = [
      "podman-network-wallabag_default.service"
      "wallabag-site-config-update.service"
    ];
    partOf = [ "podman-compose-wallabag-root.target" ];
    wantedBy = [ "podman-compose-wallabag-root.target" ];
  };

  # --- 3. NETWORKS & ROOT TARGET ---
  systemd.services."podman-network-wallabag_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.podman}/bin/podman network rm -f wallabag_default";
    };
    script = ''
      podman network inspect wallabag_default || podman network create wallabag_default
    '';
    partOf = [ "podman-compose-wallabag-root.target" ];
    wantedBy = [ "podman-compose-wallabag-root.target" ];
  };

  systemd.targets."podman-compose-wallabag-root" = {
    unitConfig.Description = "Root target for wallabag generated by compose2nix.";
    wantedBy = [ "multi-user.target" ];
  };
}
