# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Containers

  ## DB Container
  virtualisation.oci-containers.containers."wallabag-db" = {
    image = "mariadb";
    environmentFiles = [
      "/mnt/arrakis/wallabag/.env"
    ];
    volumes = [
      "/mnt/arrakis/wallabag/database:/var/lib/mysql"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"/usr/local/bin/healthcheck.sh\", \"--innodb_initialized\"]"
      "--health-interval=20s"
      "--health-timeout=3s"
      "--network-alias=db"
      "--network=wallabag_default"
    ];
  };

  ## DB Service
  systemd.services."podman-wallabag-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-wallabag_default.service"
    ];
    requires = [
      "podman-network-wallabag_default.service"
    ];
    partOf = [
      "podman-compose-wallabag-root.target"
    ];
    wantedBy = [
      "podman-compose-wallabag-root.target"
    ];
  };

  ## Redis Container
  virtualisation.oci-containers.containers."wallabag-redis" = {
    image = "redis:alpine";
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"redis-cli\", \"ping\"]"
      "--health-interval=20s"
      "--health-timeout=3s"
      "--network-alias=redis"
      "--network=wallabag_default"
    ];
  };

  ## Redis Service
  systemd.services."podman-wallabag-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-wallabag_default.service"
    ];
    requires = [
      "podman-network-wallabag_default.service"
    ];
    partOf = [
      "podman-compose-wallabag-root.target"
    ];
    wantedBy = [
      "podman-compose-wallabag-root.target"
    ];
  };

  ## Wallabag Container
  virtualisation.oci-containers.containers."wallabag-wallabag" = {
    image = "wallabag/wallabag";
    environmentFiles = [
      "/mnt/arrakis/wallabag/.env"
    ];
    volumes = [
      "/mnt/arrakis/wallabag/webserver:/var/www/wallabag/web/assets/images:rw"
    ];
    ports = [
      "8181:80/tcp"
    ];
    dependsOn = [
      "wallabag-db"
      "wallabag-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wallabag"
      "--network=wallabag_default"
    ];
  };

  ## Wallabag Service
  systemd.services."podman-wallabag-wallabag" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-wallabag_default.service"
    ];
    requires = [
      "podman-network-wallabag_default.service"
    ];
    partOf = [
      "podman-compose-wallabag-root.target"
    ];
    wantedBy = [
      "podman-compose-wallabag-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-wallabag_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f wallabag_default";
    };
    script = ''
      podman network inspect wallabag_default || podman network create wallabag_default
    '';
    partOf = [ "podman-compose-wallabag-root.target" ];
    wantedBy = [ "podman-compose-wallabag-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-wallabag-root" = {
    unitConfig = {
      Description = "Root target for wallabag generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
